### ISSUE TITLE
database management

### ISSUE THREAD

**Issue by rajrkane** [rajrkane/study#2]
These are chapter-by-chapter notes on [Database Management Systems](https://www.goodreads.com/book/show/161304.Database_Management_Systems) by Ramakrishnan. Notes are summarized in my own words.

**Comment by rrkane** [comment]
## Ch 1: Overview of database systems

First general purpose DBMS designed by Charles Bachman at GE in early 1960s. Called Integrated Data Store and formed basis of the *network data model*.

In late 1960s IBM developed the Information Management System which formed the basis of the *hierarchical data model*.

In 1970, Edgar Codd at IBM proposed the *relational data model*.

ERP (enterprise resource planning) packages on top of DBMS: Oracle, SAP

Why not use a file system?

- not enought main memory for all the data
- can't refer to more than 4 gb w/ 32 bit addressing ($2^{32} \approx 4 GB$)
- have to write special programs
- handle concurrency
- restore data to consistent state after crash while changes being made
- security

Why use a DBMS?

- data independence
- efficient data access
- data integrity and security
- data administration
- concurrent access and crash recovery
- reduced application development time

Relational model:

- the central construct is a **relation** which is basically a set of records
- a description of data in terms of a data model is a **schema**

3 levels of abstraction in a DBMS:

- **conceptual schema**: describe the data in terms of the data model of the DBMS e.g.

```{}
Students(sid:string, name:string, gpa:real)
Faculty(fid:string, name:string, sal:real)
Courses(cid:string, cname:string, credits:integer)
```

- **physical schema**: summarizes how the relations described in the conceptual schema are actually stored in storage e.g.

"Store all relations as unsorted files of records. Create indwxes on the first column of the Students, Faculty, and Courses relations."

- **external schema**: allow data access to be customized and authorized at the level of users (can be several schemas). An example view is `Courseinfo(rid:string, fname:string, enrollment:integer)`

Relational calculus: formal query language based on logic, and queries have intuitive, precise meaning
Relational algebra: formal query language based on operators for manipulation relations

DML: data manipulation language. 
DDL: data definition language (used to define external and conceptual schemas)

Transactions:

- A **transaction** is any one execution of a user program in a DMBS
- Enable concurrent execution of transactions using *locking protocol* 
- Write-Ahead Log (WAL): for incomplete transactions and system crashes, each action must be logged to the disk before the corresponding change is reflected in the database

Structure of DBMS:

1. user issues query which is parsed, presented to query optimizer which makes efficient executionn plan (tree of relational operators)
2. file and access methods layer: keeps track of pages in a file and organized info in page
3. buffer manager: brings pages from disk to memory as needed
4. disk space manager: (de)allocation, reading, writing of pages

**Comment by rrkane** [comment]
## Ch 2: intro to database design

ER model is relevant to the first three of the six steps in the database design process:

1. **requirement analysis**: what users want from the database
2. **conceptual database design**: use ER model to create a simple description of the data that closely matches how users and developers think of the data
3. **logical database design**: convert desing into a database schema in the data model of the DBMS
4. **schema refinement**
5. **physical database design**
6. **application and security design**

*entity*: object in real world. 
*entity set*: collection of similar entities (sets need not be disjoint), meaning they have the same *attributes*

Each attribute must have a domain of possible values. Choose a *key* to be a minimal set of attributes that can uniquely identify an entity in the set. Designate one candidate as the *primary key*.

*relationship*: association between entities. can have descriptive attributes
*relationship set*: set of similar relationships
*instance*: a set of relationships

Key constraints:

- arrow in ER diagram indicates that given the source entity, we can uniquely determine the relationship in which it appears (e.g. given dept can only have 1 manager). Can have these in ternary relationships as well

Participation constraints:

- e.g. whether every depratment has a manager (can be total or partial participation)

Weak entities: identified uniquely only by considering primary key of another entity called identifying owner

- weak entity set has total participation in identifying relationship set
- iwner entity set and weak entity set participate in a one to many relationship set (identifying relationshop set)

Class hierarchies: can have inheritance of attributes (ISA)

- overlap constraint: whether two subclasses are allowed to contain the same entity
- covering constraint: whether entities in the subclasses collectively include all entities in the superclass

Aggregation: relationship between collection of entities and relationships; dashed box

Choices to make: binary vs ternary relationships; aggregation vs ternary relationships; entity vs relationship; entity vs attribute

Unified modeling language (UML): constructs are drawn as diagrams unlike the ER model. Has activity diagrams, statechart diagrams, database diagrams, component diagrams, deployment diagrams, and class diagrams

**Comment by rrkane** [comment]
## Ch 3: the relational model

A database is a collection of relations. A relation consists of a *relation schema* (column heads) and a *relation instance* (table).

- Schema specifies relation's name, name of each field, domain of each field
- Instance is a set of tuples (ie records)
- *Degree* of a relation is the number of fields

Create and modify relations using SQL with the following commands: `CREATE TABLE`, `INSERT`, `DELETE`, `UPDATE`

- For `UPDATE`, the `WHERE` clause determines which rows to modify and the `SET` clause determines how to modify them

**Integrity constraint**: condition on a database schema that restrics the data that can be stored in an instance of the database

**Key constraint**: condition that a certain minimal subset of the fields of a relation is a unique identifier for a record

- **candidate key** or **key**: a set of fields that uniquely identifies a records per a key constraint
- **primary key**: a key chosen from all available candidate keys to be the preferred unique identifier for a record

Key constraints in SQL: `UNIQUE` indicates a key and `PRIMARY KEY` indicates a primary key. 

- **Foreign key** must match the primary key of the referenced relation. A foreign key could refer to the same relation. In SQL: `FOREIGN KEY`

Tricky to handle foreign key violations. Say a row is deleted and had rows from other relations referring to it. Options: 1) Delete the other rows as well 2) Disallow the row deletion 3) Set the offending column of the other rows to some default or null value

ER to relational:

- Entities and relationships are straightforward
- Can avoid creating a distinct table for a relationship set by using a key constraint to include the information about the relationship set in the table corresponding to the entity set
- Many participation constraints require table constraints or assertions
- For weak entity sets, set the primary key to take the key of the owning entity along with any unique identifier withing the table for the weak entity set
- 2 approaches for ISA hierarchies: 1) map each entity set to a distinct relation 2) create relations just for the subclasses (not always doable)

**Comment by rrkane** [comment]
## Ch 4: relational algebra and calculus

Relational algebra: queries are procedural/operational

- Select ($\sigma$): specify tuples to retain through a selection condition. e.g. $\sigma_{\text{rating}>8}(52)$, where $52$ is an instance of a relation
- Project ($\pi$): extract columns from a relation. e.g. $\pi_{\text{sname,rating}}(52)$
- Union: $R \cup S$ gives a relation instance with all tuples that occur in either instance $R$ or instance $S$; the two instances should be *union-compatible*
- Intersection $R \cap S$ gives a relation instance with all tuples that occur in both instances
- Set difference $R - S$ gives a relation instance containing all tuples that occur in $R$ but not in $S$
- Cross product $R \times S$ gives relation instance whose schema contains all fields of $R$ followed by all fields of $S$
- Condition join $R \bowtie_c S = \sigma_c(R\times S)$
  - If it's an equijoin, ie if the join condition consists solely of equalities, one of the reduntant fields is dropped
  - Natural join is an equijoin in which eqaulities are specified on all fields having the same name in both relation instances
- Division: REVISIT

Relational calculus: queries are declarative/nonprocedural

- A tuple relational calculus (TRC) query has the form $\{T|p(T)\}$ where $T$ is a tuple variable (a var that takes on tuples of a particular schema as values) and $p(T)$ is a formula describing $T$
  - Atomic formula (where $a,b$ attributes of tuple variables $R,S$, $Rel$ is a relation name, $*$ is an operator):
    - $R \in Rel$
    - $R.a * S.b$
    - $R.a * \text{constant}$
  - A formula is one of the following (recursive) (where $p,q$ are formulas and $R$ is a variable):
    - any atomic formula
    - one of: $\neg p, p \wedge q, p \vee q, p \implies q$
    - $\exists R(p(R))$
    - $\forall R(p(R))$
  - Queries are evaluated on a given instance of the database
- A domain relational calculus (DRC) query has the form $\{(x_1,x_2,...,x_n)|p((x_1,x_2,...x_n))\}$ where each $x_i$ is either a domain variable or a constant and a DRC formula is denoted by $p((x_1,x_2,...,x_n))$
  - Atomic formula ($x,y$ domain variables and $*$ operator):
    - $(x_1,x_2,...,x_n)\in Rel$ where $Rel$ is a relation with $n$ attributes
    - $x * y$
    - $x * \text{constant}$
  - A formula is one of the following (recursive) (where $p,q$ are formulas and $X$ is a variable):
    - any atomic formula
    - one of: $\neg p, p \wedge q, p \vee q, p \implies q$
    - $\exists X(p(X))$
    - $\forall X(p(X))$

Every query that can be expressed in relational algebra can also be expressed in relational calculus. 

Calculus queries need to be restricted to be *safe*.

Every safe query that can be expressed in relational calculus can also be expressed in relational algebra.

**Comment by rrkane** [comment]
## Ch 5: SQL: queries, constraints, triggers

Form of a basic SQL query:

```{sql}
SELECT [DISTINCT] select-list
FROM from-list
WHERE qualification
```

- Such a query intuitively corresponds to a relational algebra expression.
- The query returns a relation itself, which is a multiset of rows
- `from-list` is a list of table names. Table names can be followed by a range variable
- `select-list` is a list of expressions involving column names of tables named in the `from-list`
- `qualification` is a boolean combination of conditions

How is the query evaluated? (naively -- this strategy can be optimized by DBMS)

1. Compute the cross-product of the tables in the from-list.
2. Delete rows in the cross-product that fail the qualification conditions.
3. Delete all columns that do not appear in the select-list.
4. If DISTINCT is specified, eliminate duplicate rows.

Can do pattern matching with the `LIKE` and `SIMILAR` operatorS and the `%` and `_` wild-card symbols.

Set manipulation constructs: `UNION`, `INTERSECT`, `EXCEPT`

- To retain duplicates in a union, use `UNION ALL`

Other set operations: `IN`, `ANY`, `ALL`, `EXISTS`

**Nested queries**: query with an embedded subquery. Usually appear in `WHERE` clause, sometimes in `FROM` or `HAVING` clause

2 examples of nested queries for the same result:

```{sql}
SELECT S.sname
FROM Sailors S
WHERE S.sid IN ( SELECT R.sid
                 FROM Reserves R
                 WHERE R.bid = 103 )
```

- subquery independent of outer query

```(sql)
SELECT S.sname
FROM Sailors S
WHERE EXISTS ( SELECT *
               FROM Reserves R
               WHERE R.bid = 103
               AND R.sid = S.sid )
```

- subquery depends on the row currently being examined

**Aggregate operators** are used to perform some computation or summarization on retrieved data. There are 5 aggregate operators which can be applied to any column of a relation:

1. `COUNT ([DISTINCT]) column`
2. `SUM ([DISTINCT]) column`
3. `AVG ([DISTINCT]) column`
4. `MAX column`
5. `MIN column`

If there is an aggregate operation, the `SELECT` clause can *only* use aggregate operations unless there is a `GROUP BY` clause. So this is illegal:

```{sql}
SELECT S.sname, MAX (S.age)
FROM Sailors S
```

Instead write this:

```{sql}
SELECT S.sname, S.age
FROM Sailors S
WHERE S.age = ( SELECT MAX (S2.age)
                FROM Sailors S2 )
```

SQL's aggregating and grouping cannot be expressed in relational algebra.

If we want to apply aggregation to each of a number of groups of rows in a relation rather than to all qualifying rows in a relation, we use the `GROUP BY` and `HAVING` clauses.

- `GROUP BY`: specify groups
- `HAVING`: specify qualifications over groups instead of rows

Aggregate operations cannot be nested.

**Table constraints**: constraint over a single table. Has form `CHECK condition`

**Domain constraints**: can create a new domain over an underlying type. For example, you can create a new domain over the `INTEGER` type with the command `CREATE DOMAIN ratingval INTEGER DEFAULT 1
CHECK ( VALUE >= 1 AND VALUE
<=
10 )`. This example also uses a CHECK constraint

Can specify a *trigger* over a database (a procedure that monitors a database and is executed when database modified in a way that matches an event specification)

**Comment by rrkane** [comment]
## Ch 8: overview of storage and indexing

In a DBMS, the basic data abstraction is a **file** (collection of records) which consists of **pages**.

External storage:

- DBMS stores data on disk/tapes and fetches it as needed into main memory
- Each page fetched is typically 4KB or 8KB.
- Cost of database operations is mainly a result of the cost of page I/O
- Disks allow retrieval at fixed cost per page. Reading pages in order of physical storage is very cheap
- Tapes are sequential access (one page after the other). Used for archiving
- Each record in a file has a unique record id (*rid*) for the disk address of the page containing that record
- **Buffer manager**  reads data into memory and writes data to disk. The **file layer** asks the buffer manager to fetch the page that it needs to process by specifying the rid
- When the file layer needs additional space for new records on file, it asks the **disk space manager** to allocate an additional disk page for the file

File organization

- Simplest file structure is a **heap file**. Records stored in random order
- An **index** organizes data records on disk to optimize retrieval
  - **Data entry** refers to the records stored in an index file. Can efficiently search an index to find desired data entries. A data entry k* with search key value k can be a store for one of 3 things:

  1. k* is an actual data record w/ search key value k
  2. k* is a (k,rid) pair where rid refers to the record with search key value k
  3. k* is a (k,rid-list) pair where rid-list refers to a list of recirds with search key value k
   - **Clustered index**: file organized so that the ordering of records is same/close to ordering of data entries in some index. Number 1) above is clustered by definition. 2) and 3) can be clustered if records sorted on search key field, but this is expensive so typically not done and left unclustered.
     - At most 1 clustered index on a collection of records
     - less expensive to maintain than fully sorted file but expensive nonetheless, so clustering should be used only for frequent queries that benefit from this
     - BAD: hashing with clustered file
   - **Primary index**: index on set of fields that includes the primary key. Other indexes are **secondary indexes**. Duplicates cannot be found in primary index but may be found in secondary indexes (this determines whether an index has the property of being **unique**)

Index data structures

- Can organize data entries by hashing on search key or with a tree that directs a search. Any of these two can be combined with the 3 alternatives for data entries.
- **Hashing**: hash on a field in order to group records in a file into buckets, where each bucket has a primary page linked in a chain to additional pages. Insert record w/ overflow page allocated as needed.
  - good for equality selections, not for range selections
- **Tree-based indexing**: data entries arranged in a sorted order by search key value. Each node is a page. Lowest level (**leaf level**) contains data entries. Non leaf pages contain node pointers. **B+ tree** ensures that all paths from root to leaf are of the same length
  - good for either type of selection

Comparing file organizations

- Heap file: good for storage efficiency, fast scanning, fast insertion of records. Slow searches, slow deletions
- Sorted file: good storage efficiency, fast searches. Slow insertion, slow deletion
- Clustered file: all advantages of storage file + efficient insertion and efficient deletion. Searches are very fast
- Unclustered tree, unclustered hash: fast searches, insertion, deletion. Slow scans and range searches (hash doesn't support range)

Composite search keys: search key with several fields. Can support broader range of queries because it matches more selection conditions. But composite index is harder to maintain because all any field can be modified. Composite index can also be larger.

**Comment by rrkane** [comment]
## Ch 9: storing data: disks and files

Memory hierarchy: primary storage (cache, main memory) -> secondary storage (magnetic disks) -> tertiary storage (optical disks, tapes)

Magnetic disks:

- direct access to desired location
- units called disk blocks. A block is a contiguous sequence of bytes. Arranged in concentric rings (tracks) on platters. Can be recorded on either side of a platter. Track divided into sectors of fixed size. Size of a disk block can be set when disk is intitialized as a multiple of the sector size.
- Only one disk head can be read or written at one time (cannot have parallel reads/writes)
- Seek time is time taken tomove disk heads to the track on which the desired block is located.
- Access time = seek time + rotational delay + transfer time
- Records read/written as part of same block. Platter spins and other blocks on the track being read/written rotate under active head. All data on track read/written in 1 revolution. After track is done, another disk head becomes active and another track in the same cylinder is read/written. Continue until all tracks in cylinder read/written, then the arm assembly moves to an adjacent cylinder
- Disk performance has been increasing 10-20% per year (slow)
- If disk fails, data is lost
- **RAID** (redundant arrays of independent disks): A **disk array** can implement **data striping**, which distributes data over several disks to maintain **redundant** information that can be used to reconstruct the contents of a failed disk
  - many different levels of RAID systems
- **Disk space manager** provides commands to allocate/deallocate and read/write a page. Size of a page is chosen to be the size of a disk block. Keeps track of which disk blocks are used and which are free.
- Allocations/deallocations create holes. Important to keep track of free blocks

Buffer manager:

- brings pages from disk to main memory as needed
- *buffer pool* is available main memory, partitioned into pages called *frames* (slots that can hold a page residing on disk)
- two variables for each frame: *pin_count* and *dirty*
  - pin_count = number of users of the page (# times the page in a given fram has been requested but not released)
  - dirty = whether the page has been modified since being brought into the buffer pool from disk
- Page requested. Buffer manager checks buffer pool to see if some frame contains the page. If so, it increments pin_count of that frame (**pinning**). If not it chooses a frame for replacement (per **replacement policy**), increments its pin_count, overwrites the disk copy of the page with the contents of the frame if dirty==true, and reads requested page into frame. Returns address of frame. 
- Replacement policy:
  - LRU (least recently used)
  - clock replacement
  - FIFO (first in first out)
  - MRU (most recently used)

Files of records:

- Heap files: data in pages is not ordered in any way. Every record has a unique rid, and every page is of the same size.
  - supported operations: create, destroy (file); insert, delete, get (record given rid); scan (all records)
  - 2 ways to keep track of pages in each heap file: linked list and directory
  - (doubly) Linked list of pages: table of pairs maintained on disk. First page of file is header page. Maintain two lists, 1 of full pages and 1 of pages w/ free space. Disadvantage is that all pages could be in list of pages w/ free space if records have variable length
  - directory of pages solves issue of free space

Page formats:

- Fixed length records: record slots are uniform and page can be divided into fixed collection of slots
- Variable length records: issue here is finding an empty slot of the right length for a new record.

Record formats:

- Fixed length records
- Variable length records: this means that some fields of a record are of variable length (NOT that a records contain different numbers of fields)

**Comment by rrkane** [comment]
## Ch 10: tree-structured indexing

**Index file**: has one record of form (first key on page, pointer to page) per page in the data file. Refer to a pair (key,pointer) as an **index entry** or just entry.

- Do binary search of index file to identify page containing the first key value that satisfies the range selection and follow the ptr to the page containing the first record with that key value.
- Then scan the data file sequentially from that point on to retrieve other qualifying records.
- Size of an entry in index file is smaller than size of a page. Only one such entry exists per page of the data file. So, index file is much smaller than data file.
- Build a tree structure on top of this to make it even faster.

**ISAM** (indexed sequential access method):

- data entries are in leaf pages and overflow pages are chained to some leaf page
- completely static except for few overflow pages
- each tree node is a disk page and all data is in leaf pages

**B+ tree**

- dynamic index structure
- leaf pages linked using page pointers, organized into doubly linked list
- balanced
- minimum occupancy of 50% guaranteed for each node except root
- almost always superior to sorted file
- non leaf nodes with m index entries contain m+1 pointers to children
- search, insertion, deletion discussed in detail in book
- height of tree depends on # data entries and size of index entries; proportional to log(#data entries)
- Adding entry one by one can be expensive. Better to bulk load data  by: sorting data entries to be inserted according to search key k; then allocating empty page to serve as root and inserting pointer to first page of sorted entires; then adding one entry to the root page for each page of the sorted data entries until root page is full; then splitting root
  - entries for leaf pages always inserted into right most index page just above the leaf level
  - cost is (# pages containing records) + (# num pages containing data entries)
